Split ui common functions to separate file
Split dzen drawing functions to separate source-able files for
consistency and abstraction. Also attempts to be more compatible for
monitor switching.

diff --git a/bin/.bin/ui/menu_bar/status_items/battery_status b/bin/.bin/ui/menu_bar/status_items/battery_status
--- a/bin/.bin/ui/menu_bar/status_items/battery_status
+++ b/bin/.bin/ui/menu_bar/status_items/battery_status
@@ -12,96 +12,57 @@
 # Useage:      $ ./battery
 # -----------------------------------------------------------------------------
 
-# Source color theme which defines color_{0-15}
+# type and name the module
+declare -A module
+module['type']='status_item'
+module['name']='battery'
+
+# make a directory to store temporary files
+readonly temp_dir=$( mktemp -p "${TMPDIR}" -d "${USER}_${module['type']}_${module['name']}-XXXX" ) || exit 1
+# name fifo after module name and store in temp_dir
+readonly fifo="${temp_dir}/${module['name']}.fifo"
+
+# Source color theme
 source "$HOME/.bin/ui/colors"
 
-# name of the panel
-readonly panel_name='battery_status_item'
-# panel font
-readonly panel_font='Source Code Pro:size=7'
-# panel fg / bg color
-readonly color_fg="${color_lightgrey}"
-readonly color_bg="${color_black}"
+# provides function update_status_item that draws a persistent status_item using dzen
+#   name, x, y, width, height, stream, font, color_fg, color_bg --> void
+#   Modifies status_item array
+#   User must kill status_item['pid'] on cleanup
+source "$HOME/.bin/ui/menu_bar/status_items/update_status_item"
 
-# make a temporary directory to store panel fifo
-readonly temp_dir=$( mktemp -p "${TMPDIR}" -d "${panel_name}-XXXX" ) || exit 1
-# name fifo after panel_name
-readonly fifo="${temp_dir}/${panel_name}.fifo"
+# associative array for storing content to be displayed
+declare -A content
 
-# associative array with information about current text
-declare -A text
-text=( ["format"]="" ["width"]="" )
-# associative array with information about panel
-declare -A panel
-panel=( ["pid"]="" ["width"]="" )
+# Updates battery status and capacity
+#   color_fg, color_bg --> void
+#   Modifies content array
+# TODO: add bg formatting
+function update_content() {
+    # get colors
+    local color_state="$1"
+    local color_capacity="$1"
 
-# Updates the text array to have a formatted info and the correct xft width
-function update_text() {
-    # set colors
-    local color_high="${color_green}"
-    local color_medium="${color_yellow}"
-    local color_low="${color_red}"
-
-    local capacity=$(cat /sys/class/power_supply/BAT0/capacity)
+    # get values
     local state=$(cat /sys/class/power_supply/BAT0/status)
+    local capacity=$(cat /sys/class/power_supply/BAT0/capacity)
 
-    # update text array
+    # change color based on capacity value
     if [[ "${capacity}" -gt 70 ]]; then
-        text["format"]="^fg(${color_fg})${state} ^fg(${color_high})${capacity}"
+        color_capacity="${color_green}"
     elif [[ "${capacity}" -gt 30 ]]; then
-        text["format"]="^fg(${color_fg})${state} ^fg(${color_medium})${capacity}"
+        color_capacity="${color_yellow}"
     else
-        text["format"]="^fg(${color_fg})${state} ^fg(${color_low})${capacity}"
+        color_capacity="${color_red}"
     fi
 
-    text["width"]=$( xftwidth "${panel_font}" "-${state} ${capacity}-" )
-}
-
-function update_panel() {
-    # panel geometry
-    local panel_x="$(( 2840 - ${text['width']} ))"
-    local panel_y='20'
-    local panel_width="${text['width']}"
-    local panel_height='40'
-    # panel x parameters
-    local panel_layer='lower'
-    local panel_monitor='1'
-
-    # dzen title
-    local dzen_args=( '-title-name' "${panel_name}" )
-    # dzen geometry
-    dzen_args+=( '-x' "${panel_x}" '-y' "${panel_y}" '-w' "${panel_width}" '-h' "${panel_height}" )
-    # dzen font
-    dzen_args+=( '-fn' "${panel_font}" '-ta' 'c' '-fg' "${color_fg}" '-bg' "${color_bg}" )
-    # dzen x parameters
-    dzen_args+=( '-e' "onstart=${panel_layer}" '-xs' "${panel_monitor}" )
-
-    # no panel running yet
-    if [[ -z "${panel['pid']}" ]]; then
-        # create new panel with current width
-        tail -f "${fifo}" > >(dzen2 "${dzen_args[@]}") &
-
-        # update panel info
-        panel['pid']=$(echo $!)
-        panel['width']=$(echo "${text['width']}")
-
-    # panel is running but doesn't have the correct width
-    elif [[ "${panel['width']}" != "${text['width']}" ]]; then
-        # kill oldpanel
-        kill "${panel['pid']}"
-
-        # create new panel with current width
-        tail -f "${fifo}" > >(dzen2 "${dzen_args[@]}") &
-
-        # update panelinfo
-        panel['pid']=$(echo $!)
-        panel['width']=$(echo "${text['width']}")
-    fi
+    content["raw"]="${state} ${capacity}"
+    content["formatted"]="^fg(${color['fg']})${state} ^fg(${color_capacity})${capacity}"
 }
 
 function finish() {
-    # kill the panel
-    kill "${panel['pid']}"
+    # kill the status_item
+    kill "${status_item['pid']}"
 
     # remove the fifo
     rm "${fifo}"
@@ -111,6 +72,25 @@ function finish() {
 }
 
 function main() {
+    # monitor settings
+    declare -A monitor
+    monitor['width']='2880'
+    monitor['height']='1800'
+    monitor['padding']='40'
+
+    # default x geometry
+    declare -A geometry
+    geometry['x']='0'
+    geometry['y']='20'
+    geometry['width']='0'
+    geometry['height']='40'
+
+    # default colors and font
+    local font='Source Code Pro:size=7'
+    declare -A color
+    color['fg']="${color_lightgrey}"
+    color['bg']="${color_black}"
+
     while
         :
     do
@@ -119,14 +99,22 @@ function main() {
             mkfifo "${fifo}" || exit 1
         fi
 
-        # update text array
-        update_text
+        # modifies ${content['raw']} and ${content['formatted']}
+        # color_fg, color_bg --> void
+        update_content "${color['fg']}" "${color['bg']}"
+        # update width and x_pos to reflect content
+        geometry['width']=$(xftwidth "${font}" "-${content['raw']}-")
+        geometry['x']="$(( ${monitor['width']} - ${monitor['padding']} - ${geometry['width']} ))"
 
-        # update panel array
-        update_panel
+        # modifies ${status_item[@]}
+        # name, x, y, width, height, stream, font, color_fg, color_bg --> void
+        update_status_item \
+            "${module['type']}_${module['name']}" \
+            "${geometry['x']}" "${geometry['y']}" "${geometry['width']}" "${geometry['height']}" \
+            "${fifo}" "${font}" "${color['fg']}" "${color['bg']}"
 
         # pipe to fifo
-        echo "${text['format']}" >"${fifo}"
+        echo "${content['formatted']}" >"${fifo}"
 
         # wait for 1 minute
         sleep 60
diff --git a/bin/.bin/ui/menu_bar/status_items/date_status b/bin/.bin/ui/menu_bar/status_items/date_status
--- a/bin/.bin/ui/menu_bar/status_items/date_status
+++ b/bin/.bin/ui/menu_bar/status_items/date_status
@@ -11,87 +11,48 @@
 # Useage:      $ sh ./clock
 # -----------------------------------------------------------------------------
 
-# Source color theme which defines color_{0-15}
+# type and name the module
+declare -A module
+module['type']='status_item'
+module['name']='date'
+
+# make a directory to store temporary files
+readonly temp_dir=$( mktemp -p "${TMPDIR}" -d "${USER}_${module['type']}_${module['name']}-XXXX" ) || exit 1
+# name fifo after module name and store in temp_dir
+readonly fifo="${temp_dir}/${module['name']}.fifo"
+
+# Source color theme
 source "$HOME/.bin/ui/colors"
 
-# name of the panel
-readonly panel_name='date_status_item'
-# panel font
-readonly panel_font='Source Code Pro:size=7'
-# panel fg / bg color
-readonly color_fg="${color_lightgrey}"
-readonly color_bg="${color_black}"
+# provides function update_status_item that draws a persistent status_item using dzen
+#   name, x, y, width, height, stream, font, color_fg, color_bg --> void
+#   Modifies status_item array
+#   User must kill status_item['pid'] on cleanup
+source "$HOME/.bin/ui/menu_bar/status_items/update_status_item"
 
-# make a temporary directory to store panel fifo
-readonly temp_dir=$( mktemp -p "${TMPDIR}" -d "${panel_name}-XXXX" ) || exit 1
-# name fifo after panel_name
-readonly fifo="${temp_dir}/${panel_name}.fifo"
+# associative array for storing content to be displayed
+declare -A content
 
-# associative array with information about current text
-declare -A text
-text=( ["format"]="" ["width"]="" )
-# associative array with information about panel
-declare -A panel
-panel=( ["pid"]="" ["width"]="" )
-
-# Updates the text array to have a formatted info and the correct xft width
-function update_text() {
+# Updates date
+#   color_fg, color_bg --> void
+#   Modifies content array
+# TODO: add bg formatting
+function update_content() {
     # set colors
+    local color_fg="$1"
     local color_weekday="${color_lightgrey}"
     local color_date="${color_blue}"
     local color_time="${color_yellow}"
     local color_ampm="${color_lightgrey}"
 
     # update text array
-    text["format"]=$( date +"^fg(${color_weekday})%A ^fg(${color_date})%d ^fg(${color_time})%I^fg(${color_fg}):^fg(${color_time})%M ^fg(${color_ampm})%p" )
-    text["width"]=$( xftwidth "${panel_font}" "$(date +'-%A %d %I:%M %p-')" )
-}
-
-function update_panel() {
-    # panel geometry
-    local panel_x="$(( 1440 - ${text['width']} / 2 ))"
-    local panel_y='20'
-    local panel_width="${text['width']}"
-    local panel_height='40'
-    # panel x parameters
-    local panel_layer='lower'
-    local panel_monitor='1'
-
-    # dzen title
-    local dzen_args=( '-title-name' "${panel_name}" )
-    # dzen geometry
-    dzen_args+=( '-x' "${panel_x}" '-y' "${panel_y}" '-w' "${panel_width}" '-h' "${panel_height}" )
-    # dzen font
-    dzen_args+=( '-fn' "${panel_font}" '-ta' 'c' '-fg' "${color_fg}" '-bg' "${color_bg}" )
-    # dzen x parameters
-    dzen_args+=( '-e' "onstart=${panel_layer}" '-xs' "${panel_monitor}" )
-
-    # no panel running yet
-    if [[ -z "${panel['pid']}" ]]; then
-        # create new panel with current width
-        tail -f "${fifo}" > >(dzen2 "${dzen_args[@]}") &
-
-        # update panel info
-        panel['pid']=$(echo $!)
-        panel['width']=$(echo "${text['width']}")
-
-    # panel is running but doesn't have the correct width
-    elif [[ "${panel['width']}" != "${text['width']}" ]]; then
-        # kill oldpanel
-        kill "${panel['pid']}"
-
-        # create new panel with current width
-        tail -f "${fifo}" > >(dzen2 "${dzen_args[@]}") &
-
-        # update panelinfo
-        panel['pid']=$(echo $!)
-        panel['width']=$(echo "${text['width']}")
-    fi
+    content["raw"]="$(date +'%A %d %I:%M %p')"
+    content["formatted"]=$( date +"^fg(${color_weekday})%A ^fg(${color_date})%d ^fg(${color_time})%I^fg(${color_fg}):^fg(${color_time})%M ^fg(${color_ampm})%p" )
 }
 
 function finish() {
-    # kill the panel
-    kill "${panel['pid']}"
+    # kill the status_item
+    kill "${status_item['pid']}"
 
     # remove the fifo
     rm "${fifo}"
@@ -101,6 +62,25 @@ function finish() {
 }
 
 function main() {
+    # monitor settings
+    declare -A monitor
+    monitor['width']='2880'
+    monitor['height']='1800'
+    monitor['padding']='40'
+
+    # default x geometry
+    declare -A geometry
+    geometry['x']='0'
+    geometry['y']='20'
+    geometry['width']='0'
+    geometry['height']='40'
+
+    # default colors and font
+    local font='Source Code Pro:size=7'
+    declare -A color
+    color['fg']="${color_lightgrey}"
+    color['bg']="${color_black}"
+
     while
         :
     do
@@ -109,14 +89,22 @@ function main() {
             mkfifo "${fifo}" || exit 1
         fi
 
-        # update text array
-        update_text
+        # modifies ${content['raw']} and ${content['formatted']}
+        # color_fg, color_bg --> void
+        update_content "${color['fg']}" "${color['bg']}"
+        # update width and x_pos to reflect content
+        geometry['width']=$(xftwidth "${font}" "-${content['raw']}-")
+        geometry['x']="$(( (${monitor['width']} - ${geometry['width']}) / 2 ))"
 
-        # update panel array
-        update_panel
+        # modifies ${status_item[@]}
+        # name, x, y, width, height, stream, font, color_fg, color_bg --> void
+        update_status_item \
+            "${module['type']}_${module['name']}" \
+            "${geometry['x']}" "${geometry['y']}" "${geometry['width']}" "${geometry['height']}" \
+            "${fifo}" "${font}" "${color['fg']}" "${color['bg']}"
 
         # pipe to fifo
-        echo "${text['format']}" >"${fifo}"
+        echo "${content['formatted']}" >"${fifo}"
 
         # wait for 1 minute
         sleep 60
diff --git a/bin/.bin/ui/menu_bar/status_items/mpd_status b/bin/.bin/ui/menu_bar/status_items/mpd_status
--- a/bin/.bin/ui/menu_bar/status_items/mpd_status
+++ b/bin/.bin/ui/menu_bar/status_items/mpd_status
@@ -12,40 +12,43 @@
 # Usage:      $ ./music
 # -----------------------------------------------------------------------------
 
-# Source color theme which defines color_{0-15}
+# type and name the module
+declare -A module
+module['type']='status_item'
+module['name']='mpd'
+
+# make a directory to store temporary files
+readonly temp_dir=$( mktemp -p "${TMPDIR}" -d "${USER}_${module['type']}_${module['name']}-XXXX" ) || exit 1
+# name fifo after module name and store in temp_dir
+readonly fifo="${temp_dir}/${module['name']}.fifo"
+
+# Source color theme
 source "$HOME/.bin/ui/colors"
 
-# name of the panel
-readonly panel_name='mpd_status_item'
-# panel font
-readonly panel_font='Source Code Pro:size=7'
-# panel fg / bg color
-readonly color_fg="${color_lightgrey}"
-readonly color_bg="${color_black}"
+# provides function update_status_item that draws a persistent status_item using dzen
+#   name, x, y, width, height, stream, font, color_fg, color_bg --> void
+#   Modifies status_item array
+#   User must kill status_item['pid'] on cleanup
+source "$HOME/.bin/ui/menu_bar/status_items/update_status_item"
 
-# make a temporary directory to store panel fifo
-readonly temp_dir=$( mktemp -p "${TMPDIR}" -d "${panel_name}-XXXX" ) || exit 1
-# name fifo after panel_name
-readonly fifo="${temp_dir}/${panel_name}.fifo"
+# associative array for storing content to be displayed
+declare -A content
 
-# associative array with information about current text
-declare -A text
-text=( ["format"]="" ["width"]="" )
-# associative array with information about panel
-declare -A panel
-panel=( ["pid"]="" ["width"]="" )
-
-# Updates the text array to have a formatted info and the correct xft width
-function update_text() {
+#
+#   color_fg, color_bg --> void
+#   Modifies content array
+# TODO: add bg formatting
+function update_content() {
     # set colors
+    local color_fg="$1"
     local color_artist="${color_blue}"
     local color_title="${color_yellow}"
     local color_album="${color_lightgrey}"
 
     # nothing is currently playing or paused
     if [[ -z "$(mpc current)" ]]; then
-        text["format"]="^fg(${color_fg})Playlist Empty"
-        text["width"]=$( xftwidth "${panel_font}" '-Playlist Empty-' )
+        content['raw']='Playlist Empty'
+        content['formatted']="^fg(${color_fg})Playlist Empty"
 
     # something is playing or paused
     else
@@ -56,92 +59,50 @@ function update_text() {
 
         # has artist, title and album
         if [[ -n "${artist}" && -n "${title}" && -n "${album}" ]]; then
-            text["format"]="^fg(${color_artist})${artist}^fg(${color_fg}) - ^fg(${color_title})${title}^fg(${color_fg}) - ^fg(${color_album})${album}"
-            text["width"]=$( xftwidth "${panel_font}" "-${artist} - ${title} - ${album}-" )
+            content['raw']="${artist} - ${title} - ${album}"
+            content['formatted']="^fg(${color_artist})${artist}^fg(${color_fg}) - ^fg(${color_title})${title}^fg(${color_fg}) - ^fg(${color_album})${album}"
 
         # has artist and title but not album
         elif [[ -n "${artist}" && -n "${title}" ]]; then
-            text["format"]="^fg(${color_artist})${artist}^fg(${color_fg}) - ^fg(${color_title})${title}"
-            text["width"]=$( xftwidth "${panel_font}" "-${artist} - ${title}-" )
+            content['raw']="${artist} - ${title}"
+            content['formatted']="^fg(${color_artist})${artist}^fg(${color_fg}) - ^fg(${color_title})${title}"
 
         # has artist and album but not title
         elif [[ -n "${artist}" && -n "${album}" ]]; then
-            text["format"]="^fg(${color_artist})${artist}^fg(${color_fg}) - ^fg(${color_album})${album}"
-            text["width"]=$( xftwidth "${panel_font}" "-${artist} - ${album}-" )
+            content['raw']="${artist} - ${album}"
+            content['formatted']="^fg(${color_artist})${artist}^fg(${color_fg}) - ^fg(${color_album})${album}"
 
         # has title and album but not artist
         elif [[ -n "${title}" && -n "${album}" ]]; then
-            text["format"]="^fg(${color_title})${title}^fg(${color_fg}) - ^fg(${color_album})${album}"
-            text["width"]=$( xftwidth "${panel_font}" "-${title} - ${album}-" )
+            content['raw']="${title} - ${album}"
+            content['formatted']="^fg(${color_title})${title}^fg(${color_fg}) - ^fg(${color_album})${album}"
 
         # has only artist
         elif [[ -n "${artist}" ]]; then
-            text["format"]="^fg(${color_artist})${artist}"
-            text["width"]=$( xftwidth "${panel_font}" "-${artist}-" )
+            content['raw']="${artist}"
+            content['formatted']="^fg(${color_artist})${artist}"
 
         # has only title
         elif [[ -n "${title}" ]]; then
-            text["format"]="^fg(${color_title})${title}"
-            text["width"]=$( xftwidth "${panel_font}" "-${title}-" )
+            content['raw']="${title}"
+            content['formatted']="^fg(${color_title})${title}"
 
         # has only album
         elif [[ -n "${album}" ]]; then
-            text["format"]="^fg(${color_album})${album}"
-            text["width"]=$( xftwidth "${panel_font}" "-${album}-" )
+            content['raw']="${album}"
+            content['formatted']="^fg(${color_album})${album}"
 
         # no artist, title or album
         else
-            text["format"]="^fg(${color_fg})Unknown"
-            text["width"]=$( xftwidth "${panel_font}" '-Unknown-' )
+            content['raw']='Unknown'
+            content['formatted']="^fg(${color_fg})Unknown"
         fi
     fi
 }
 
-function update_panel() {
-    # panel geometry
-    local panel_x='40'
-    local panel_y='20'
-    local panel_width="${text['width']}"
-    local panel_height='40'
-    # panel x parameters
-    local panel_layer='lower'
-    local panel_monitor='1'
-
-    # dzen title
-    local dzen_args=( '-title-name' "${panel_name}" )
-    # dzen geometry
-    dzen_args+=( '-x' "${panel_x}" '-y' "${panel_y}" '-w' "${panel_width}" '-h' "${panel_height}" )
-    # dzen font
-    dzen_args+=( '-fn' "${panel_font}" '-ta' 'c' '-fg' "${color_fg}" '-bg' "${color_bg}" )
-    # dzen x parameters
-    dzen_args+=( '-e' "onstart=${panel_layer}" '-xs' "${panel_monitor}" )
-
-    # no panel running yet
-    if [[ -z "${panel['pid']}" ]]; then
-        # create new panel with current width
-        tail -f "${fifo}" > >(dzen2 "${dzen_args[@]}") &
-
-        # update panel info
-        panel['pid']=$(echo $!)
-        panel['width']=$(echo "${text['width']}")
-
-    # panel is running but doesn't have the correct width
-    elif [[ "${panel['width']}" != "${text['width']}" ]]; then
-        # kill oldpanel
-        kill "${panel['pid']}"
-
-        # create new panel with current width
-        tail -f "${fifo}" > >(dzen2 "${dzen_args[@]}") &
-
-        # update panelinfo
-        panel['pid']=$(echo $!)
-        panel['width']=$(echo "${text['width']}")
-    fi
-}
-
 function finish() {
-    # kill the panel
-    kill "${panel['pid']}"
+    # kill the status_item
+    kill "${status_item['pid']}"
 
     # remove the fifo
     rm "${fifo}"
@@ -151,6 +112,25 @@ function finish() {
 }
 
 function main() {
+    # monitor settings
+    declare -A monitor
+    monitor['width']='2880'
+    monitor['height']='1800'
+    monitor['padding']='40'
+
+    # default x geometry
+    declare -A geometry
+    geometry['x']='0'
+    geometry['y']='20'
+    geometry['width']='0'
+    geometry['height']='40'
+
+    # default colors and font
+    local font='Source Code Pro:size=7'
+    declare -A color
+    color['fg']="${color_lightgrey}"
+    color['bg']="${color_black}"
+
     while
         :
     do
@@ -159,14 +139,22 @@ function main() {
             mkfifo "${fifo}" || exit 1
         fi
 
-        # update text array
-        update_text
+        # modifies ${content['raw']} and ${content['formatted']}
+        # color_fg, color_bg --> void
+        update_content "${color['fg']}" "${color['bg']}"
+        # update width and x_pos to reflect content
+        geometry['width']=$(xftwidth "${font}" "-${content['raw']}-")
+        geometry['x']="${monitor['padding']}"
 
-        # update panel array
-        update_panel
+        # modifies ${status_item[@]}
+        # name, x, y, width, height, stream, font, color_fg, color_bg --> void
+        update_status_item \
+            "${module['type']}_${module['name']}" \
+            "${geometry['x']}" "${geometry['y']}" "${geometry['width']}" "${geometry['height']}" \
+            "${fifo}" "${font}" "${color['fg']}" "${color['bg']}"
 
         # pipe to fifo
-        echo "${text['format']}" >"${fifo}"
+        echo "${content['formatted']}" >"${fifo}"
 
         # wait for mpd player event
         mpc idle player >/dev/null
