Change fave script to use mktemp
Change fave script to use mktemp instead of target.tmp. This improves
the defense of the script if run in readonly filesystem.

diff --git a/bin/.bin/fave b/bin/.bin/fave
--- a/bin/.bin/fave
+++ b/bin/.bin/fave
@@ -11,6 +11,22 @@
 # favorites file
 readonly fave_file="$HOME/music/.faves"
 
+function fave_target_check() {
+    # file to operate on
+    local target="$1"
+
+    if [[ ! -e "${target}" ]]; then
+        touch "${target}"
+
+        if [[ $? -eq 0 ]]; then
+            echo "Tracking favorite songs in '${target}'"
+        else
+            echo "Could not create '${target}!'" >&2
+            exit 1
+        fi
+    fi
+}
+
 function song_info() {
     # get individual mpc current fields for formatting
     local artist=$( mpc -f "[%artist%]" | head -n 1 )
@@ -44,6 +60,9 @@ function song_info() {
         # has only album
     elif [[ -n "${album}" ]]; then
         echo "${album}"
+        # has nothing
+    else
+        echo ""
     fi
 }
 
@@ -90,18 +109,21 @@ function fave_remove() {
 
     # check if current song is favorited
     if grep -Fq "${current_song}" "${target}"; then
-        # print all lines except current song to target.tmp
-        grep -Fv "${current_song}" "${target}" > "${target}.tmp"
-        # overwrite target with target.tmp
-        mv "${target}.tmp" "${target}"
+        # make a temporary file
+        readonly fave_tmp=$( mktemp --tmpdir "faves.XXX" )
+        # print all lines except current song to fave_tmp
+        grep -Fv "${current_song}" "${target}" > "${fave_tmp}"
+
+        # overwrite target with fave_tmp
+        mv "${fave_tmp}" "${target}"
 
         # check if temp file successfuly overwrote target file
         if [[ $? -eq 0 ]]; then
             echo "rm '${current_song}'"
         else
-            echo "Unable to move '${target}.tmp' to '${target}'!" >&2
+            echo "Unable to move '${fave_tmp}' to '${target}'!" >&2
             # target was not overwritten so delete the temp file
-            rm "${target}.tmp" || echo "Count not remove '${target}.tmp'!" >&2
+            rm "${fave_tmp}" || echo "Count not remove '${fave_tmp}'!" >&2
             exit 1
         fi
     else
@@ -117,11 +139,8 @@ function fave_list() {
     cat "${target}"
 }
 
-# check for favorites file; create if not found
-if [[ ! -e "${fave_file}" ]]; then
-    touch "${fave_file}" || { echo "Could not create '${fave_file}!'" >&2; exit 1; }
-    echo "Tracking favorite songs in '${fave_file}'"
-fi
+# check if target file exists; create if not found
+fave_target_check "${fave_file}"
 
 case $1 in
     # add current song to target file
